x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  filebrowser:
    container_name: filebrowser
    image: muwn/filebrowser:latest
    restart: unless-stopped
    environment:
      - FB_PORT=80
      - FB_ADDRESS=
      - FB_LOG=stdout
      - FB_DATABASE=/database/filebrowser.db
      - FB_ROOT=/srv
      - TZ=Asia/Shanghai
    ports:
      - "8080:80"
    volumes:
      - ./volumes/config/:/etc/filebrowser/
      - ./volumes/data/:/database/
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.01'
          memory: 10M
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","curl -s http://127.0.0.1:80/health > /dev/null 2>&1" ]
