x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  filebrowser:
    container_name: filebrowser
    image: muwn/filebrowser:latest
    restart: unless-stopped
    environment:
      - FB_DATABASE=/data/database/filebrowser.db
      - FB_ROOT=/data/files
      - TZ=Asia/Shanghai
    ports:
      - "8080:80"
    volumes:
      - ./volumes/config/:/etc/filebrowser/
      - ./volumes/data/:/data/
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.01'
          memory: 10M
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 80" ]
