x-default-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 5s
  retries: 2
  start_period: 10s

services:
  frps:
    container_name: frps
    image: muwn/frps:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "7000-7010:7000-7010"
    volumes:
      - ./volumes/frp/:/etc/frp/
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.01'
          memory: 10M
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 7000" ]

  fp-multiuser:
    container_name: fp-multiuser
    image: muwn/fp-multiuser:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./volumes/fp-multiuser/:/etc/fp-multiuser/
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.01'
          memory: 10M
    healthcheck:
      <<: *default-healthcheck
      test: [ "CMD-SHELL","nc -z 127.0.0.1 7200" ]