name: amazoncorretto
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version' # see https://github.com/corretto/corretto-docker/blob/main/21/jdk/debian/Dockerfile
        required: true
        default: '21.0.10.7-1'

jobs:
  get-dockerfiles:
    runs-on: ubuntu-latest
    outputs:
      dockerfiles: ${{ steps.list-dockerfiles.outputs.dockerfiles }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List all Dockerfile-*
        id: list-dockerfiles
        run: |
          IMAGE_NAME=amazoncorretto
          DOCKERFILES=$(find ./${IMAGE_NAME} -name 'Dockerfile*' -type f | sed 's|.*/||' | sort | jq -R -s -c 'split("\n")[:-1]')
          echo "dockerfiles=${DOCKERFILES}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: get-dockerfiles
    strategy:
      matrix:
        dockerfile: ${{ fromJson(needs.get-dockerfiles.outputs.dockerfiles) }}
      fail-fast: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare
        id: prepare
        run: |
          FULL_VERSION=${{ github.event.inputs.version }}
          # 截取主版本号 (如 21.0.10.7-1 -> 21.0.10)
          VERSION=$(echo "${FULL_VERSION}" | cut -d'.' -f1-3)
          IMAGE_NAME=amazoncorretto
          DOCKERFILE=${{ matrix.dockerfile }}
          VERSION_SUFFIX=$(echo "${DOCKERFILE}" | sed 's/Dockerfile-//')
          TAGS="${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:${VERSION}-${VERSION_SUFFIX}"
          echo "build_args=version=${FULL_VERSION}" >> $GITHUB_OUTPUT
          echo "image-name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "dockerfile=${DOCKERFILE}" >> $GITHUB_OUTPUT
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ steps.prepare.outputs.image-name }}
          file: ./${{ steps.prepare.outputs.image-name }}/${{ steps.prepare.outputs.dockerfile }}
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/riscv64,linux/s390x
          push: true
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          enable-url-completion: true
          readme-filepath: ./${{ steps.prepare.outputs.image-name }}/README.md
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.prepare.outputs.image-name }}